import { App } from '@octokit/app'
import { createClient } from '@supabase/supabase-js'
import Groq from 'groq-sdk'

const app = new App({
  appId: process.env.GITHUB_APP_ID!,
  privateKey: process.env.GITHUB_PRIVATE_KEY!.replace(/\\n/g, '\n'),
  webhooks: {
    secret: process.env.GITHUB_WEBHOOK_SECRET!,
  },
})

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY })

export async function GET() {
  return Response.json({ ok: true, status: 'PRDraft webhook is live' })
}

async function generatePRDescription(diff: string, prTitle: string): Promise<string> {
  const prompt = `You are a senior software engineer writing a pull request description.
Analyze this diff and write a clear, structured PR description.

PR Title: ${prTitle}

Diff:
${diff.slice(0, 8000)}

Write the description in this exact format:

## What changed
[2-4 bullet points describing what actually changed in the code]

## Why
[1-2 sentences explaining the reason for this change]

## How to test
[2-3 bullet points with specific steps to test this change]

## Notes
[Any edge cases, concerns, or things reviewers should watch for. Write "None" if not applicable]

Rules:
- Be specific, not generic
- Reference actual function names, file names, or line numbers from the diff
- Do not say "this PR" or "this commit"
- Keep it under 200 words total`

  const result = await groq.chat.completions.create({
    model: 'llama-3.3-70b-versatile',
    messages: [{ role: 'user', content: prompt }],
    max_tokens: 500,
  })
  return result.choices[0]?.message?.content ?? ''
}

export async function POST(req: Request) {
  const body = await req.text()
  const signature = req.headers.get('x-hub-signature-256') ?? ''
  const event = req.headers.get('x-github-event') ?? ''

  // Verify webhook signature
  try {
    await app.webhooks.verifyAndReceive({
      id: req.headers.get('x-github-delivery') ?? '',
      name: event as any,
      signature,
      payload: body,
    })
  } catch (err) {
    console.error('Webhook verification failed:', err)
    return Response.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const payload = JSON.parse(body)

  // Only handle PR opened events
  if (event !== 'pull_request' || payload.action !== 'opened') {
    return Response.json({ ok: true, skipped: true })
  }

  const installationId = payload.installation?.id
  const repoFullName = payload.repository?.full_name
  const prNumber = payload.pull_request?.number
  const prTitle = payload.pull_request?.title ?? 'Untitled PR'

  if (!installationId || !repoFullName || !prNumber) {
    return Response.json({ error: 'Missing fields' }, { status: 400 })
  }

  try {
    // Check or create install record
    const { data: install } = await supabase
      .from('installs')
      .select('*')
      .eq('installation_id', installationId)
      .single()

    // Upsert install
    await supabase.from('installs').upsert({
      installation_id: installationId,
      account_login: payload.installation?.account?.login ?? 'unknown',
      account_type: payload.installation?.account?.type ?? 'User',
      pr_count: (install?.pr_count ?? 0) + 1,
    })

    // Enforce free tier cap (5 PRs/month)
    if (install && install.plan === 'free' && install.pr_count >= 5) {
      console.log(`Free tier cap hit for installation ${installationId}`)
      return Response.json({ ok: true, capped: true })
    }

    // Get octokit for this installation
    const octokit = await app.getInstallationOctokit(installationId)

    // Fetch the diff
    const { data: diffData } = await octokit.request(
      'GET /repos/{owner}/{repo}/pulls/{pull_number}',
      {
        owner: repoFullName.split('/')[0],
        repo: repoFullName.split('/')[1],
        pull_number: prNumber,
        headers: { accept: 'application/vnd.github.v3.diff' },
      }
    )

    const diff = diffData as unknown as string

    if (!diff || diff.length < 10) {
      return Response.json({ ok: true, skipped: 'empty diff' })
    }

    // Generate description
    const description = await generatePRDescription(diff, prTitle)

    // Post back to PR
    await octokit.request(
      'PATCH /repos/{owner}/{repo}/pulls/{pull_number}',
      {
        owner: repoFullName.split('/')[0],
        repo: repoFullName.split('/')[1],
        pull_number: prNumber,
        body: description + '\n\n---\n*Generated by [PRDraft](https://prdraft.carrd.co)*',
      }
    )

    // Log the event
    await supabase.from('pr_events').insert({
      installation_id: installationId,
      repo_full_name: repoFullName,
      pr_number: prNumber,
    })

    console.log(`✅ Generated description for ${repoFullName}#${prNumber}`)
    return Response.json({ ok: true })

  } catch (err) {
    console.error('Error processing PR:', err)
    return Response.json({ error: 'Internal error' }, { status: 500 })
  }
}
